# Generated by Django 6.0.1 on 2026-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=2, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
