# Generated by Django 6.0.1 on 2026-02-18 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_remove_product_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='card',
            new_name='cart',
        ),
    ]
